#!/bin/sh -e
# 
# postinst maintainer script for the Debian tex-common package.
#
# Copyright (C) 2004 by Frank Küster <frank@kuesterei.ch>. 
# Copyright (C) 2012-2014 by Norbert Preining <preining@debian.org>
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# This file is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to: The Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# On Debian GNU/Linux System you can find a copy of the GNU General Public
# License in "/usr/share/common-licenses/GPL".

umask 022

#
# definitions of necessary trees
TEXMFSYSVARDIR=/var/lib/texmf
TEXMFTREES="/usr/share/texmf $TEXMFSYSVARDIR"
FULLTEXMFTREES="$TEXMFTREES /usr/share/texlive/texmf-dist"

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>


# Give a name to the first commandline argument
action=$1
trigger=$2

. /usr/share/debconf/confmodule
db_version 2.0

cleanup()
{
  rc=$?
  [ -n "$tempdir" ] && rm -rf "$tempdir"
  exit $rc
}

#
# dpkg-query returns 1 if the package is not installed or not
# present, and echos out strange things, we have to override this.
dhit_package_configured()
{
    stat=$(dpkg-query -W -f='${Status}' $1 2>/dev/null || true)
    case "$stat" in
        "install ok installed")
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

dhit_base_bin_configured ()
{
    we_are_ready=0
    if ! dhit_package_configured texlive-binaries ; then
        return 1
    fi
    dhit_package_configured texlive-base
}

dhit_build_format ()
{
    tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
    printf "Building format(s) $*.\n\tThis may take some time... "
    if fmtutil-sys --no-error-if-no-engine=luajittex "$@" > $tempfile 2>&1 ; then
        rm -f $tempfile
        echo "done."
    else
        exec >&2
        echo
        echo "fmtutil-sys failed. Output has been stored in"
        echo "$tempfile"
        echo "Please include this file if you report a bug."
        echo
        exit 1
    fi
}

run_mtxrun_if_possible()
{
    if dhit_package_configured context ; then
        tempfile=$(mktemp -p /tmp mtxrun.XXXXXXXX)
        printf "Running mtxrun --generate. This may take some time... "
        if mtxrun --generate > $tempfile 2>&1 ; then
            rm -f $tempfile
            echo "done."
        else
            exec >&2
            echo
            echo "mtxrun --generate failed. Output has been stored in"
            echo "$tempfile"
            echo "Please include this file if you report a bug."
            echo
            exit 1
	    fi
    fi
}

do_triggers() 
{
    # vars used to record what we have done already, not to make
    # it two times
    DONE_FULL_LSR=0
    DONE_MTXRUN=0
    # currently we only support only triggers for updmap.d and
    # hyphen.d changes
    # because all the other calls are quite fast 
    # - call all the update-* scripts (it doesn't hurt)
    # - go through all the triggers and call the respective fmtutil/updmap
    #   calls.

    # in any case call the update-* calls
    update-language
    update-fmtutil
    #
    # the following triggers are reacted upon and in that order:
    # - texmf-lsr: call mktexlsr if present
    # - texmf-lsrfull: call mktexlsr if present
    # - texmf-map: call updmap-sys
    # - texmf-hyphen: if texmf-format hasn't been triggered call 
    #                 fmtutil-sys --byhyphen ...
    case " $trigger " in
        *" texmf-lsrfull "*)
            if dhit_base_bin_configured ; then
                tempfile=$(mktemp -p /tmp mktexlsr.XXXXXXXX)
                printf "Running mktexlsr. This may take some time... "
                if mktexlsr $FULLTEXMFTREES > $tempfile 2>&1 ; then
                    DONE_FULL_LSR=1
                    rm -f $tempfile
                    echo "done."
                else
                    exec >&2
                    echo
                    echo "mktexlsr $FULLTEXMFTREES failed. Output has been stored in"
                    echo "$tempfile"
                    echo "Please include this file if you report a bug."
                    echo
                    exit 1
                fi
                if [ $DONE_MTXRUN = 0 ] ; then
                    run_mtxrun_if_possible
                    DONE_MTXRUN=1
                fi
            fi
        ;;
    esac
    # do NOT merge these two cases into one, from dpkg's trigger.txt:
    # Generally each trigger name should be tested for separately, as the
    # postinst will often be called for several triggers at once.
    case " $trigger " in
        *" texmf-lsr "*)
            # only to lsr if we haven't done lsrfull
            if [ $DONE_FULL_LSR = 0 ] ; then
                if dhit_base_bin_configured; then
                    tempfile=$(mktemp -p /tmp mktexlsr.XXXXXXXX)
                    printf "Running mktexlsr. This may take some time... "
                    if mktexlsr $TEXMFTREES > $tempfile 2>&1 ; then
                        rm -f $tempfile
                        echo "done."
                    else
                        exec >&2
                        echo
                        echo "mktexlsr $TEXMFTREES failed. Output has been stored in"
                        echo "$tempfile"
                        echo "Please include this file if you report a bug."
                        echo
                        exit 1
                    fi
                    if [ $DONE_MTXRUN = 0 ] ; then
                        run_mtxrun_if_possible
                        DONE_MTXRUN=1
                    fi
                fi
            fi
        ;;
    esac
    # do NOT merge these two cases into one, from dpkg's trigger.txt:
    # Generally each trigger name should be tested for separately, as the
    # postinst will often be called for several triggers at once.
    case " $trigger " in
        *" texmf-map "*) 
            if dhit_base_bin_configured; then
                tempfile=$(mktemp -p /tmp updmap.XXXXXXXX)
                printf "Running updmap-sys. This may take some time... "
                # call updmap with --nohash so that no ls-R files
                # are created in /usr/local/share/texmf/
                # see bug report #607857
                # instead of that we call mktexlsr $TEXMFSYSVARDIR 
                # afterwards. This can be done without checks as
                # we know that dhit_texlive_binaries_configured and
                # since mktexlsr and updmap are in the same package
                # and we checked for updmap already
                if updmap-sys --nohash > $tempfile 2>&1 ; then
                    rm -f $tempfile
                    echo "done."
                    tempfile=$(mktemp -p /tmp mktexlsr.XXXXXXXX)
                    printf "Running mktexlsr $TEXMFSYSVARDIR ... "
                    if mktexlsr $TEXMFSYSVARDIR > $tempfile 2>&1 ; then
                        rm -f $tempfile
                        echo "done."
                    else
                        exec >&2
                        echo
                        echo "mktexlsr $TEXMFSYSVARDIR failed. Output has been stored in"
                        echo "$tempfile"
                        echo "Please include this file if you report a bug."
                        echo
                        exit 1
                    fi
                else
                    exec >&2
                    echo
                    echo "updmap-sys failed. Output has been stored in"
                    echo "$tempfile"
                    echo "Please include this file if you report a bug."
                    echo
                    echo "Sometimes, not accepting conffile updates in /etc/texmf/updmap.d"
                    echo "causes updmap-sys to fail.  Please check for files with extension"
                    echo ".dpkg-dist or .ucf-dist in this directory" 
                    echo
                    exit 1
        	    fi
            fi
        ;;
    esac
    # do NOT merge these two cases into one, from dpkg's trigger.txt:
    # Generally each trigger name should be tested for separately, as the
    # postinst will often be called for several triggers at once.
    case " $trigger " in
        *" texmf-hyphen "*) 
            if dhit_base_bin_configured; then
                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
                printf "Building latex-based formats --byhyphen $(kpsewhich language.dat).\n\tThis may take some time... "
                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.dat)" > $tempfile 2>&1 ; then
                    rm -f $tempfile
                    echo "done."
                else
                    exec >&2
                    echo
                    echo "fmtutil-sys failed. Output has been stored in"
                    echo "$tempfile"
                    echo "Please include this file if you report a bug."
                    echo
                    exit 1
                fi
                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
                printf "Building e-tex based formats --byhyphen $(kpsewhich language.def).\n\tThis may take some time... "
                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --byhyphen "$(kpsewhich language.def)" > $tempfile 2>&1 ; then
                    rm -f $tempfile
                    echo "done."
                else
                    exec >&2
                    echo
                    echo "fmtutil-sys failed. Output has been stored in"
                    echo "$tempfile"
                    echo "Please include this file if you report a bug."
                    echo
                    exit 1
                fi
            fi
        ;;
    esac
    # do NOT merge these two cases into one, from dpkg's trigger.txt:
    # Generally each trigger name should be tested for separately, as the
    # postinst will often be called for several triggers at once.
    case " $trigger " in
        *" texmf-fmtrefresh "*) 
            if dhit_base_bin_configured; then
                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
                printf "Refreshing all formats.\n\tThis may take some time... "
                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --refresh > $tempfile 2>&1 ; then
                    rm -f $tempfile
                    echo "done."
                else
                    exec >&2
                    echo
                    echo "fmtutil-sys failed. Output has been stored in"
                    echo "$tempfile"
                    echo "Please include this file if you report a bug."
                    echo
                    exit 1
                fi
            fi
        ;;
    esac
    # do NOT merge these two cases into one, from dpkg's trigger.txt:
    # Generally each trigger name should be tested for separately, as the
    # postinst will often be called for several triggers at once.
    case " $trigger " in
        *" texmf-fmtall "*) 
            if dhit_base_bin_configured; then
                tempfile=$(mktemp -p /tmp fmtutil.XXXXXXXX)
                printf "Rebuilding all formats.\n\tThis may take some time... "
                if fmtutil-sys --no-error-if-no-format --no-error-if-no-engine=luajittex --all > $tempfile 2>&1 ; then
                    rm -f $tempfile
                    echo "done."
                else
                    exec >&2
                    echo
                    echo "fmtutil-sys failed. Output has been stored in"
                    echo "$tempfile"
                    echo "Please include this file if you report a bug."
                    echo
                    exit 1
                fi
            fi
        ;;
    esac
}


#################################################################
# Here starts the real action
#################################################################


case $action in
    triggered)
        do_triggers
        ;;

    configure|reconfigure)

        # if we are upgrading from before 4, remove the preinst created
        # backup of the symlink
        if dpkg --compare-versions "$trigger" lt "4" ; then
            if [ -L /usr/share/texmf/doc.dpkg-remove ] ; then
                rm -f /usr/share/texmf/doc.dpkg-remove
            fi
        fi

        # create/update texmf.cnf
        update-texmf

        # remove outdated thailatex babel.sty
        if [ -f $TEXMFSYSVARDIR/tex/generic/babel/babel.sty ] ; then
            echo "Removing outdated babel.sty from thailatex."
            rm $TEXMFSYSVARDIR/tex/generic/babel/babel.sty
            rmdir --ignore-fail-on-non-empty $TEXMFSYSVARDIR/tex/generic/babel
            rmdir --ignore-fail-on-non-empty $TEXMFSYSVARDIR/tex/generic
            rmdir --ignore-fail-on-non-empty $TEXMFSYSVARDIR/tex
        fi

        #
        # call trigger action
        # that calls mktexlsr if possible, and update-*
        # we set the triggers updmap.d
        #
        trigger="texmf-lsr texmf-map texmf-fmtall"
        do_triggers

        # create empty dirs in /usr/local/share/
        if [ ! -e /usr/local/share/texmf ] ; then
            if mkdir -p /usr/local/share/texmf 2>/dev/null ; then
                chown root:staff /usr/local/share/texmf
                chmod 2775 /usr/local/share/texmf
            fi
        fi

        # remove out dated dir /etc/texmf/language.d
        if [ -d /etc/texmf/language.d ] ; then 
            rmdir --ignore-fail-on-non-empty /etc/texmf/language.d/
        fi
        ;;
    *)
        ;;
esac


#DEBHELPER#

### Local Variables:
### perl-indent-level: 4
### tab-width: 4
### indent-tabs-mode: nil
### End:
# vim:set tabstop=4 expandtab: #
