#!/bin/sh
#
# dh_installtexfonts
# 
# transform calls from the old dh_installtexfonts syntax to the new
# dh_installtex syntax
#
# Norbert Preining
# 2006
#

echo "dh_installtexfonts is deprecated. Please use dh_installtex!" >&2
echo "This is a shell script converting the call syntax for " >&2
echo "dh_installtexfonts into the syntax for dh_installtex." >&2

newargs=""
for i in "$@" ; do
    case "$i" in
    	--flavor=*)
	    foo=$(echo "$i" | sed -e 's/--flavor=/--flavor=map:/')
	    newargs="$newargs $foo"
	    ;;
	Map=*|MixedMap=*|map=*|mixedmap=*)
	    foo=$(echo "$i" | sed -e 's/=/,/')
	    newargs="$newargs map=$foo"
	    ;;
	*.cfg|*.cfg=*)
	    newargs="$newargs mapfile=$i"
	    ;;
	*)
	    newargs="$newargs $i"
	    ;;
    esac
done

echo "Please use dh_installtex in your scripts!" >&2
echo "Calling: dh_installtex $newargs" >&2

dh_installtex $newargs

