.TH UPDATE-FMTUTIL 8
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
update-fmtutil \- shell script to generate /var/lib/texmf/web2c/fmtutil.cnf
.SH SYNOPSIS
.B update-fmtutil
.I "[options]"
.br
.SH DESCRIPTION
This manual page documents briefly the
.BR update-fmtutil
command.
This manual page was written for the Debian GNU/Linux distribution
because the original script was designed for Debian packaging system.
.PP
.B update-fmtutil
is a shell script to generate /var/lib/texmf/web2c/fmtutil.cnf from files
matching the pattern /etc/texmf/fmt.d/*.cnf.
.PP
The tex-common package provides 00tex.cnf only and other TeX-related packages
can provide their own .cnf files in /etc/texmf/fmt.d/. These files should have
a name starting with a two-digit integer indicating the order in which
update-fmtutil is supposed to read them.
.PP
A user who wants to customize /var/lib/texmf/web2c/fmtutil.cnf should add, 
for example, 22local-foo.cnf in /etc/texmf/fmt.d/ and run 'update-fmtutil'.
.SH OPTIONS
.TP
.B \-v
Show verbose messages (deprecated; will be the default setting soon).
.TP
.B \--check
Executes additional checks that all necessary files are present in the
kpathsea database. Don't use this in maintainer scripts.
.SH AUTHOR
This manual page was written by Atsuhito Kohda <kohda@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
