#!/bin/sh -e
#
# update-texmf-config
# script used in maintainer script for updating the config files
# updmap.cfg, language.dat, fmtutil.cnf, and calling the respective
# triggers to allow tex-common trigger action to be run.
#
# Copyright (C) 2009-2014 Norbert Preining
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING. If not, write to the
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA  02110-1301 USA.

DOLSR=off
DOLSRFULL=off
DOHYPHEN=off
DOUPDMAP=off
DOFMTALL=off
DOFMTREFRESH=off

# for upgrading purpose we accept language as synonym for hyphen, and
# updmap for map
while [ $# -ne 0 ]; do
  case $1 in
    hyphen|language)
      DOHYPHEN=on
      shift;;
    map|updmap)
      DOUPDMAP=on
      shift;;
    lsr)
      DOLSR=on
      shift;;
    lsrfull)
      DOLSRFULL=on
      shift;;
    fmtrefresh)
      DOFMTREFRESH=on
      shift;;
    fmtall)
      DOFMTALL=on
      shift;;
    *)
      echo "unknown option: $1"
      exit 1
      ;;
  esac
done

# call the resepctive triggers, make sure that
# we turn of superficial things on the way
# thus, the order here is important!
if [ $DOLSRFULL = on ] ; then
  DOLSR=off
  dpkg-trigger texmf-lsrfull
fi
if [ $DOLSR = on ] ; then
  dpkg-trigger texmf-lsr
fi
if [ $DOFMTALL = on ] ; then
  DOFMTREFRESH=off
  DOHYPHEN=off
  dpkg-trigger texmf-fmtall
fi
if [ $DOFMTREFRESH = on ] ; then
  DOHYPHEN=off
  dpkg-trigger texmf-fmtrefresh
fi
if [ $DOHYPHEN = on ] ; then
  dpkg-trigger texmf-hyphen
fi
#
# not needed anymore, we are using a file trigger
# we probably should warn during build time that
# update-texmf-conf map is not needed anymore
#if [ $DOUPDMAP = on ] ; then
#  dpkg-trigger texmf-map
#fi

# vim:set expandtab tabstop=2: #
