.TH update-fontlang 8 "2006-11-03" "Updating TeX config files"

.SH NAME
update-updmap, update-language, update-fmtutil, update-fontlang \- update various TeX related config files

.SH SYNOPSIS
.B update-[language,updmap,fmtutil]
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains briefly the usage of the three TeX configuration
update programs
.B update-language, update-updmap,
and \fBupdate-fmtutil\fP.
.PP
The
.B update-fontlang
script should not be called directly, only via the three described links.
For a more in depth description please see the documentation TeX on Debian in
.I /usr/share/doc/tex-common/TeX-on-Debian.txt.gz
(also available as HTML and PDF).

The programs \fBupdate-language\fP, \fBupdate-updmap\fP, and 
\fBupdate-fmtutil\fP create/update the configuration files \fIlanguage.dat\fP,
\fIupdmap.cfg\fP, and \fIfmtutil.cnf\fP, respectively. These files define
the hyphenation patterns to be loaded into LaTeX related TeX formats
(language.dat), the outline fonts available for the TeX system (updmap.sys),
and the list of formats to be created (fmtutil.cnf).

These programs can be used either in system wide mode if called by root, or
in a user-specific mode if called by a user without write permissions to
system areas.
.SH OPTIONS
.B
.IP -c|--conf-dir
directory where the user-specific configuration is looked for in 
user-specific mode
.B
.IP -o|--output-file
file to write the output to. Per default in system-wide mode 
\fBupdate-language\fP writes to 
\fI/var/lib/texmf/tex/generic/config/language.dat\fP,
\fBupdate-updmap\fP writes to 
\fI/var/lib/texmf/web2c/updmap.cfg\fP, and
\fBupdate-fmtutil\fP writes to
\fI/var/lib/texmf/web2c/fmtutil.cnf\fP.
.B
.IP --checks
perform sanity checks on the generated config file. Don't use this
in maintainer scripts.
.B
.IP --quiet
don't write anything to the standard output during normal operation
.B
.IP --help
display this help message and exit
.B
.IP --version
output version information and exit

.SH USAGE

In system-wide mode all three programs merge those files
("configuration snippets") with a specific extension in the respective
configuration directories to produce the final file. These
configuration directories and extensions are \fIlanguage.d\fP and
\fB.cnf\fP for update-language, \fIupdmap.d\fP and \fB.cfg\fP for
update-updmap, and \fIfmt.d\fP and \fB.cnf\fP for update-fmtutil. In
system-wide mode these directories are searched in \fI/etc/texmf/\fP.
Both TeX add-on packages and local administrators can add files to
these directories.

If a package that provides such snippets is removed but not purged,
including the snippet will likely break the system.  To prevent the
inclusion in these cases, snippets installed by \fIpackages\fP have to
contain a magic header, 

# -_- DebPkgProvidedMaps -_-

which local administrators should \fInot\fP remove.  From the files
with a magic header, only those files which are also listed in one of
the files in
.I /var/lib/tex-common/language-cnf/
for update-language,
.I /var/lib/tex-common/fontmap-cfg/
for update-updmap, and
.I /var/lib/tex-common/fmtutil-cnf/
for update-fmtutil are actually included into the final output
file. This way local changes to the configuration can be preserved
while the package is in state `rc'.  For details about that mechanism,
package maintainers should consult the Debian TeX Policy.

The user-specific mode provides a way a non-admin user can override
system-wide settings.  In this mode,
\fBupdate-language\fP writes to 
\fITEXMFVAR/tex/generic/config/language.dat\fP,
\fBupdate-updmap\fP writes to 
\fITEXMFVAR/web2c/updmap.cfg\fP, and
\fBupdate-fmtutil\fP writes to
\fITEXMFVAR/web2c/fmtutil.cnf\fP, where \fITEMXFVAR\fP is normally
\fI$HOME/.texmf-var/\fP. 
Furthermore, files present within the user-specific configuration
directories are included in addition to the files present in the
system-wide configuration directories.  In case the same filename
exists in the system-wide configuration directory and the
user-specific configuration directory, the user-specific file is used
instead of the system-wide one.  These directories are
\fITEXMFCONFIG/language.d\fP for \fBupdate-language\fP,
\fITEXMFCONFIG/updmap.d\fP for \fBupdate-updmap\fP,
\fITEXMFCONFIG/fmt.d\fP for \fBupdate-fmtutil\fP, where
\fITEMXFCONFIG\fP is normally \fI$HOME/.texmf-config/\fP.  Note that changes
introduced by updates of packages are not automatically propagated to the
user's files.

.SH FILES
.TP
.B /var/lib/texmf/tex/generic/config/language.dat
This file is generated/updated by \fBupdate-language\fP in system-wide
mode and contains a lists the hyphenation patters loaded into
LaTeX based formats by \fBfmtutil-sys\fP.
.TP
.B /var/lib/texmf/web2c/updmap.cfg
This file is generated/updated by \fBupdate-updmap\fP in system-wide
mode and contains a list of map files to be included
into the list of outline fonts generated by \fBupdmap-sys\fP.
.TP
.B /var/lib/texmf/web2c/fmtutil.cnf
This file is generated/updated by \fBupdate-fmtutil\fP in system-wide
mode and contains a list of formats to be generated by \fBfmtutil-sys\fP.
.TP
.B /etc/texmf/language.d/\fIname\fP.cnf
Input files for \fBupdate-language\fP
.TP
.B /etc/texmf/updmap.d/\fIname\fP.cfg
Input files for \fBupdate-updmap\fP
.TP
.B /etc/texmf/fmt.d/\fIname\fP.cnf
Input files for \fBupdate-fmtutil\fP
.TP
.B /var/lib/tex-common/language-cnf/\fIpackage\fP.list
lists the \fI/etc/texmf/language.d/\fP file installed by \fIpackage\fP.
.TP
.B /var/lib/tex-common/fontmap-cfg/\fIpackage\fP.list
lists the \fI/etc/texmf/updmap.d/\fP file installed by \fIpackage\fP.
.TP
.B /var/lib/tex-common/fmtutil-cnf/\fIpackage\fP.list
lists the \fI/etc/texmf/fmt.d/\fP file installed by \fIpackage\fP.

.SH SEE ALSO

.TP
.B fmtutil(1), fmtutil-sys(1), updmap(1), updmap-sys(1)
The programs actually using the generated configuration files.
.TP
.B TeX on Debian Documentation
to be found in \fI/usr/share/tex-common/TeX-on-Debian.txt.gz\fP (also
available as HTML and PDF), describing in more detail how to setup
and maintain a TeX system. It also includes details on user-specific
configuration.
.TP
.B Debian TeX Policy
to be found in \fI/usr/share/doc/tex-common/Debian-TeX-Policy.txt.gz\fP
(also available as HTML and PDF), describing the internals and the
suggested policy.
.TP
.B dh_installtex(1)
a debhelper script for managing the installation of files into the
system-wide configuration directories to be used in other Debian packages.

.SH AUTHOR
This manual page was written by Norbert Preining <preining@debian.org>
for the Debian distribution (and may be used by others).
