.TH UPDATE-FONTLANG 8
.SH NAME
update-fontlang \- helper script for tex-common
.SH SYNOPSIS
.B update-language
.I "[options]"
.br
.B update-updmap
.I "[options]"
.br
.B update-fmtutil
.I "[options]"
.br
.SH DESCRIPTION
.BR update-fontlang
should be called as 
.B update-updmap
or
.B update-language
or
.B update-fmtutil.
Depending on the name it is called with, it behaves as described in
the respective manual pages.  It should not be called directly
.PP
.SH SEE ALSO
.PP
.BR update-language (8),
.BR update-updmap (1),
.BR update-fmtutil (1);
further information can be found in the Debian TeX Policy, 
.B /usr/share/doc/tex-common/Debian-TeX-Policy.txt.gz
.PP
.SH AUTHOR
This manual page was written by Frank K\[:u]ster <frank@debian.org>,
for the Debian GNU/Linux system, but may be used by others under the
terms of the GNU General Public License, either version 2 or any later
version. 
